### ISSUE TITLE
CoolProp.State.State class not working on Python 3

### ISSUE THREAD

**Issue by spinnau** [ibell/coolprop#81]
Creating a state object like

``` python
from CoolProp.State import State

S = State('Water', dict(T=400, P=100))
```

in _CoolProp version 4.0.0beta_ (self compiled on Linux) works fine on Python 2.7. But on Python 3.3 I got an TypeError, that the Fluid name should be of type _bytes_ not _str_. Using _bytes_ for the Fluid argument

``` python
S = State(b'Water', dict(T=400, P=100))
```

results in another error message caused by conversion between _bytes_ and _str_.

```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    S = State(b'Water', dict(T=400, P=100))
  File "CoolProp.pyx", line 815, in CoolProp.CoolProp.State.__init__ (build/temp.linux-x86_64-3.3/pyrex/CoolProp/CoolProp.cpp:24537)
    self.set_Fluid(Fluid)
  File "CoolProp.pyx", line 862, in CoolProp.CoolProp.State.set_Fluid (build/temp.linux-x86_64-3.3/pyrex/CoolProp/CoolProp.cpp:25136)
    add_REFPROP_fluid(self.Fluid.encode('ascii'))
AttributeError: 'bytes' object has no attribute 'encode'
```

I think the best solution might be to change the type of the Fluid argument to _str_, to have a consistent interface for `CoolProp.State.State` and `CoolProp.CoolProp.Props` classes. This would also allow to run the same code on Python 2 and on Python 3.

What do you think about this?

**Comment by ibell** [comment]
Works for me.  If you can test this and make sure it works in 2.x and 3.x,
I'm fine with this change.  Are you comfortable with git/pull requests?
Alternatively you can make the change in the web interface.  Also, if you
are at it, it would be good to go through all the functions in CoolProp.pyx
and make this change to eliminate all the rest of the string conversion
problems between 2.x and 3.x.

**Comment by spinnau** [comment]
As there are no release branches I have tried to start work on master branch. The python wrapper compiles without any error for Python 2.7 and Python 3.3 (with gcc 4.8.2 and cython 0.19.2), but I got an ImportError on both Python versions:

```
>>> import CoolProp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: ./CoolProp.so: undefined symbol: _Z7get_colRKSt6vectorIS_IdSaIdEESaIS1_EEj
>>> 
```

I have not yet figured out, which changes between _4.0.0beta_ source zip-file and master branch caused this error. Maybe missed linking a library in setup.py?

**Comment by ibell** [comment]
That's a weird error.  Did you do anything funny to install?  Or just the normal python setup.py install in the wrappers/Python folder?  Can you try to clean out your site-packages/CoolProp folder and the build folder in the python folder? It might be trying to mix 3.x object files and 2.x object files which I think are incompatible. Or the name mangling is handled somehow differently.

**Comment by spinnau** [comment]
I had run the _python setup.py build_ command in the _wrappers/Python_ folder and tested directly in _wrappers/Python/build/lib.linux.../CoolProp_. But I got the same error after trying _python setup.py install_ with normal installation in the python site-packages folder. I have also deleted the _wrappers/Python/build_ folder before each test.

The mentioned ImportError firstly occurs on f4624e92fc (Added matrix routines). The previous commit a4b179d358 works fine.

**Comment by ibell** [comment]
Hmm, py 2.7 works for me with the master on windows, I'll check linux on my
box

**Comment by ibell** [comment]
Works on py 2.7 on my xubuntu virtual box image.  Weird.

**Comment by jowr** [comment]
Hi, please note that there is a linux script `install-linux.sh`. I needed to make that file because the python-only approach did not work reliably for me. 

Jorrit

**Comment by ibell** [comment]
@jowr Do you recall what was not reliable?  IMHO, this is a fairly serious
problem that we should get to the bottom of.  CP builds fine for me on
xubuntu with py2.7

**Comment by jowr** [comment]
In my distribution (debian testing and python 2.7), I got some problems with the permissions and hence I wrote the script, which also calls the python functions with the following changes:
- Build as normal user: `python setup.py build`
- Remove system packages: `sudo rm -r /usr/local/lib/python2.7/dist-packages/CoolProp*`
- Install as superuser: `sudo python setup.py install`
- Make files readable for normal users: `sudo chmod -R a+r /usr/local/lib/python2.7/dist-packages/CoolProp`

My problem was that I did not want to build the software as root, but root-rights are needed for a system-wide installation.

**Comment by ibell** [comment]
Ah ok, that makes sense, but I guess for me I just ran sudo python setup.py
install so I avoided that problem.  But otherwise, yes, you cannot install
into dist-packages as a normal user it seems

**Comment by spinnau** [comment]
I don't think it has anything to do with permissions, as the build and installation works properly for me before f4624e92fc. But I have also tried to `chmod a+r` the _site-packages/CoolProp_ folder without any change.

A look with `nm` on the created _CoolProp.so_ library file showed the undefined symbol as mentioned before:

```
...
00000000000e9690 T _Z7REFPROPSsSsdSsdSs
00000000000ee750 T _Z7REFPROPccdcdPc
0000000000130a90 T _Z7_Props1PcS_
                 U _Z7get_colRKSt6vectorIS_IdSaIdEESaIS1_EEj
00000000001c84f0 T _Z7get_colRKSt6vectorIS_IdSaIdEESaIS1_EEm
00000000001c7d70 T _Z7get_rowRKSt6vectorIS_IdSaIdEESaIS1_EEm
000000000012c380 T _Z7rho_Icedd
...
```

And with demangled names:

```
...
00000000000e9690 T REFPROP(std::string, std::string, double, std::string, double, std::string)
00000000000ee750 T REFPROP(char, char, double, char, double, char*)
0000000000130a90 T _Props1(char*, char*)
                 U get_col(std::vector<std::vector<double, std::allocator<double> >, std::allocator<std::vector<double, std::allocator<double> > > > const&, unsigned int)
00000000001c84f0 T get_col(std::vector<std::vector<double, std::allocator<double> >, std::allocator<std::vector<double, std::allocator<double> > > > const&, unsigned long)
00000000001c7d70 T get_row(std::vector<std::vector<double, std::allocator<double> >, std::allocator<std::vector<double, std::allocator<double> > > > const&, unsigned long)
000000000012c380 T rho_Ice(double, double)
...
```

**Comment by ibell** [comment]
Interesting.  py 2.7 or py 3.0?

**Comment by ibell** [comment]
Perhaps the issue is that in the header get_col takes an unsigned int, and in the implementation, it takes a size_t - maybe it then can't figure out the overloading.  Try setting the size_t in MatrixMath.cpp's get_col to unsigned int?

**Comment by ibell** [comment]
I dont have access to my linux box right now, but I'll bet money that's the issue.  The cleanest way is to change the unsigned int in MatrixMath.h to size_t and add the necessary includes

**Comment by spinnau** [comment]
@ibell The error was excatly the same for me on Python 2.7 and 3.3. Changing the types of `col` and `row` parameters in `get_row` and `get_col` from `unsigned int` to `size_t` in _MatrixMath.h_ does the trick. Thank you very much.

Now master branch works for me both in Python 2.7 and 3.3. So i can have a look at the _byte/str_ conversion problem for State class on Python 3.

**Comment by ibell** [comment]
Ok, I have pushed the fix to MatrixMath.h, should work from master with new
code, can you please test?  If it works, please close the ticket :)

**Comment by spinnau** [comment]
Your changes works fine for me. The bug with the CoolProp.State.State class not working on Python 3 is still open. I will try to fix it.

**Comment by ibell** [comment]
Good to hear about the size_t working, it would be great if you could fix
the other part too.
